version: "3.9"

services:
  uniconnect-db:
    image: postgres:16
    container_name: uniconnect-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  uniconnect-api:
    build: .
    container_name: uniconnect-api
    depends_on:
      uniconnect-db:
        condition: service_healthy
    environment:
      DB_HOST: uniconnect-db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

    ports:
      - "8080:8080"
